import { CountryPhoneCode } from '../../model/country';

export const countriesPhoneCodeData: CountryPhoneCode[] = [
  {
    name: 'Afghanistan',
    phoneCode: '+93',
    numeric: '004',
    totalDigits: 9,
  },
  {
    name: 'Albania',
    phoneCode: '+355',
    numeric: '008',
    totalDigits: 9,
  },
  {
    name: 'Algeria',
    phoneCode: '+213',
    numeric: '012',
    totalDigits: 9,
  },
  {
    name: 'American Samoa',
    phoneCode: '+1684',
    numeric: '016',
    totalDigits: 10,
  },
  {
    name: 'Andorra',
    phoneCode: '+376',
    numeric: '020',
    totalDigits: 9,
  },
  {
    name: 'Angola',
    phoneCode: '+244',
    numeric: '024',
    totalDigits: 9,
  },
  {
    name: 'Anguilla',
    phoneCode: '+1264',
    numeric: '660',
    totalDigits: 10,
  },
  {
    name: 'Antigua and Barbuda',
    phoneCode: '+1268',
    numeric: '028',
    totalDigits: 10,
  },
  {
    name: 'Argentina',
    phoneCode: '+54',
    numeric: '032',
    totalDigits: 10,
  },
  {
    name: 'Armenia',
    phoneCode: '+374',
    numeric: '051',
    totalDigits: 8,
  },
  {
    name: 'Aruba',
    phoneCode: '+297',
    numeric: '533',
    totalDigits: 9,
  },
  {
    name: 'Australia',
    phoneCode: '+61',
    numeric: '036',
    totalDigits: 9,
  },
  {
    name: 'Austria',
    phoneCode: '+43',
    numeric: '040',
    totalDigits: 10,
  },
  {
    name: 'Azerbaijan',
    phoneCode: '+994',
    numeric: '031',
    totalDigits: 9,
  },
  {
    name: 'Bahamas',
    phoneCode: '+1242',
    numeric: '044',
    totalDigits: 10,
  },
  {
    name: 'Bahrain',
    phoneCode: '+973',
    numeric: '048',
    totalDigits: 8,
  },
  {
    name: 'Bangladesh',
    phoneCode: '+880',
    numeric: '050',
    totalDigits: 10,
  },
  {
    name: 'Barbados',
    phoneCode: '+1246',
    numeric: '052',
    totalDigits: 10,
  },
  {
    name: 'Belarus',
    phoneCode: '+375',
    numeric: '112',
    totalDigits: 9,
  },
  {
    name: 'Belgium',
    phoneCode: '+32',
    numeric: '056',
    totalDigits: 9,
  },
  {
    name: 'Belize',
    phoneCode: '+501',
    numeric: '084',
    totalDigits: 8,
  },
  {
    name: 'Benin',
    phoneCode: '+229',
    numeric: '204',
    totalDigits: 8,
  },
  {
    name: 'Bermuda',
    phoneCode: '+1441',
    numeric: '060',
    totalDigits: 10,
  },
  {
    name: 'Bhutan',
    phoneCode: '+975',
    numeric: '064',
    totalDigits: 8,
  },
  {
    name: 'Bolivia',
    phoneCode: '+591',
    numeric: '068',
    totalDigits: 8,
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    phoneCode: '+599',
    numeric: '535',
    totalDigits: 9,
  },
  {
    name: 'Bosnia and Herzegovina',
    phoneCode: '+387',
    numeric: '070',
    totalDigits: 8,
  },
  {
    name: 'Botswana',
    phoneCode: '+267',
    numeric: '072',
    totalDigits: 8,
  },
  {
    name: 'Brazil',
    phoneCode: '+55',
    numeric: '076',
    totalDigits: 10,
  },
  {
    name: 'British Indian Ocean Territory',
    phoneCode: '+246',
    numeric: '086',
    totalDigits: 9,
  },
  {
    name: 'British Virgin Islands',
    phoneCode: '+1284',
    numeric: '092',
    totalDigits: 10,
  },
  {
    name: 'Brunei',
    phoneCode: '+673',
    numeric: '096',
    totalDigits: 8,
  },
  {
    name: 'Bulgaria',
    phoneCode: '+359',
    numeric: '100',
    totalDigits: 9,
  },
  {
    name: 'Burkina Faso',
    phoneCode: '+226',
    numeric: '854',
    totalDigits: 8,
  },
  {
    name: 'Burundi',
    phoneCode: '+257',
    numeric: '108',
    totalDigits: 8,
  },
  {
    name: 'Cambodia',
    phoneCode: '+855',
    numeric: '116',
    totalDigits: 9,
  },
  {
    name: 'Cameroon',
    phoneCode: '+237',
    numeric: '120',
    totalDigits: 9,
  },
  {
    name: 'Canada',
    phoneCode: '+1',
    numeric: '124',
    totalDigits: 10,
  },
  {
    name: 'Cape Verde',
    phoneCode: '+238',
    numeric: '132',
    totalDigits: 7,
  },
  {
    name: 'Cayman Islands',
    phoneCode: '+1345',
    numeric: '136',
    totalDigits: 10,
  },
  {
    name: 'Central African Republic',
    phoneCode: '+236',
    numeric: '140',
    totalDigits: 8,
  },
  {
    name: 'Chad',
    phoneCode: '+235',
    numeric: '148',
    totalDigits: 8,
  },
  {
    name: 'Chile',
    phoneCode: '+56',
    numeric: '152',
    totalDigits: 9,
  },
  {
    name: 'China',
    phoneCode: '+86',
    numeric: '156',
    totalDigits: 11,
  },
  {
    name: 'Christmas Island',
    phoneCode: '+61',
    numeric: '162',
    totalDigits: 9,
  },
  {
    name: 'Cocos (Keeling) Islands',
    phoneCode: '+61',
    numeric: '166',
    totalDigits: 9,
  },
  {
    name: 'Colombia',
    phoneCode: '+57',
    numeric: '170',
    totalDigits: 10,
  },
  {
    name: 'Comoros',
    phoneCode: '+269',
    numeric: '174',
    totalDigits: 7,
  },
  {
    name: 'Congo',
    phoneCode: '+242',
    numeric: '178',
    totalDigits: 9,
  },
  {
    name: 'Cook Islands',
    phoneCode: '+682',
    numeric: '184',
    totalDigits: 5,
  },
  {
    name: 'Costa Rica',
    phoneCode: '+506',
    numeric: '188',
    totalDigits: 8,
  },
  {
    name: 'Croatia',
    phoneCode: '+385',
    numeric: '191',
    totalDigits: 9,
  },
  {
    name: 'Cuba',
    phoneCode: '+53',
    numeric: '192',
    totalDigits: 8,
  },
  {
    name: 'Curaçao',
    phoneCode: '+599',
    numeric: '531',
    totalDigits: 9,
  },
  {
    name: 'Cyprus',
    phoneCode: '+357',
    numeric: '196',
    totalDigits: 8,
  },
  {
    name: 'Czech Republic',
    phoneCode: '+420',
    numeric: '203',
    totalDigits: 9,
  },
  {
    name: 'Denmark',
    phoneCode: '+45',
    numeric: '208',
    totalDigits: 8,
  },
  {
    name: 'Djibouti',
    phoneCode: '+253',
    numeric: '262',
    totalDigits: 8,
  },
  {
    name: 'Dominica',
    phoneCode: '+1767',
    numeric: '212',
    totalDigits: 10,
  },
  {
    name: 'Dominican Republic',
    phoneCode: '+1809',
    numeric: '214',
    totalDigits: 10,
  },
  {
    name: 'Dominican Republic',
    phoneCode: '+1829',
    numeric: '214',
    totalDigits: 10,
  },
  {
    name: 'Dominican Republic',
    phoneCode: '+1849',
    numeric: '214',
    totalDigits: 10,
  },
  {
    name: 'Ecuador',
    phoneCode: '+593',
    numeric: '218',
    totalDigits: 9,
  },
  {
    name: 'Egypt',
    phoneCode: '+20',
    numeric: '818',
    totalDigits: 10,
  },
  {
    name: 'El Salvador',
    phoneCode: '+503',
    numeric: '222',
    totalDigits: 8,
  },
  {
    name: 'Equatorial Guinea',
    phoneCode: '+240',
    numeric: '226',
    totalDigits: 9,
  },
  {
    name: 'Eritrea',
    phoneCode: '+291',
    numeric: '232',
    totalDigits: 7,
  },
  {
    name: 'Estonia',
    phoneCode: '+372',
    numeric: '233',
    totalDigits: 8,
  },
  {
    name: 'Eswatini',
    phoneCode: '+268',
    numeric: '748',
    totalDigits: 8,
  },
  {
    name: 'Ethiopia',
    phoneCode: '+251',
    numeric: '231',
    totalDigits: 9,
  },
  {
    name: 'Falkland Islands',
    phoneCode: '+500',
    numeric: '238',
    totalDigits: 9,
  },
  {
    name: 'Faroe Islands',
    phoneCode: '+298',
    numeric: '234',
    totalDigits: 6,
  },
  {
    name: 'Fiji',
    phoneCode: '+679',
    numeric: '242',
    totalDigits: 7,
  },
  {
    name: 'Finland',
    phoneCode: '+358',
    numeric: '246',
    totalDigits: 9,
  },
  {
    name: 'France',
    phoneCode: '+33',
    numeric: '250',
    totalDigits: 9,
  },
  {
    name: 'French Guiana',
    phoneCode: '+594',
    numeric: '254',
    totalDigits: 9,
  },
  {
    name: 'French Polynesia',
    phoneCode: '+689',
    numeric: '258',
    totalDigits: 6,
  },
  {
    name: 'Gabon',
    phoneCode: '+241',
    numeric: '266',
    totalDigits: 8,
  },
  {
    name: 'Gambia',
    phoneCode: '+220',
    numeric: '270',
    totalDigits: 7,
  },
  {
    name: 'Georgia',
    phoneCode: '+995',
    numeric: '268',
    totalDigits: 9,
  },
  {
    name: 'Germany',
    phoneCode: '+49',
    numeric: '276',
    totalDigits: 10,
  },
  {
    name: 'Ghana',
    phoneCode: '+233',
    numeric: '288',
    totalDigits: 9,
  },
  {
    name: 'Gibraltar',
    phoneCode: '+350',
    numeric: '292',
    totalDigits: 8,
  },
  {
    name: 'Greece',
    phoneCode: '+30',
    numeric: '300',
    totalDigits: 10,
  },
  {
    name: 'Greenland',
    phoneCode: '+299',
    numeric: '304',
    totalDigits: 6,
  },
  {
    name: 'Grenada',
    phoneCode: '+1473',
    numeric: '308',
    totalDigits: 10,
  },
  {
    name: 'Guadeloupe',
    phoneCode: '+590',
    numeric: '312',
    totalDigits: 9,
  },
  {
    name: 'Guam',
    phoneCode: '+1671',
    numeric: '316',
    totalDigits: 10,
  },
  {
    name: 'Guatemala',
    phoneCode: '+502',
    numeric: '320',
    totalDigits: 8,
  },
  {
    name: 'Guernsey',
    phoneCode: '+44',
    numeric: '831',
    totalDigits: 10,
  },
  {
    name: 'Guinea',
    phoneCode: '+224',
    numeric: '324',
    totalDigits: 8,
  },
  {
    name: 'Guinea-Bissau',
    phoneCode: '+245',
    numeric: '624',
    totalDigits: 7,
  },
  {
    name: 'Guyana',
    phoneCode: '+592',
    numeric: '328',
    totalDigits: 7,
  },
  {
    name: 'Haiti',
    phoneCode: '+509',
    numeric: '332',
    totalDigits: 8,
  },
  {
    name: 'Honduras',
    phoneCode: '+504',
    numeric: '340',
    totalDigits: 8,
  },
  {
    name: 'Hong Kong',
    phoneCode: '+852',
    numeric: '344',
    totalDigits: 8,
  },
  {
    name: 'Hungary',
    phoneCode: '+36',
    numeric: '348',
    totalDigits: 9,
  },
  {
    name: 'Iceland',
    phoneCode: '+354',
    numeric: '352',
    totalDigits: 7,
  },
  {
    name: 'India',
    phoneCode: '+91',
    numeric: '356',
    totalDigits: 10,
  },
  {
    name: 'Indonesia',
    phoneCode: '+62',
    numeric: '360',
    totalDigits: 10,
  },
  {
    name: 'Iran',
    phoneCode: '+98',
    numeric: '364',
    totalDigits: 10,
  },
  {
    name: 'Iraq',
    phoneCode: '+964',
    numeric: '368',
    totalDigits: 10,
  },
  {
    name: 'Ireland',
    phoneCode: '+353',
    numeric: '372',
    totalDigits: 9,
  },
  {
    name: 'Isle of Man',
    phoneCode: '+44',
    numeric: '833',
    totalDigits: 10,
  },
  {
    name: 'Israel',
    phoneCode: '+972',
    numeric: '376',
    totalDigits: 9,
  },
  {
    name: 'Italy',
    phoneCode: '+39',
    numeric: '380',
    totalDigits: 10,
  },
  {
    name: 'Ivory Coast',
    phoneCode: '+225',
    numeric: '384',
    totalDigits: 8,
  },
  {
    name: 'Jamaica',
    phoneCode: '+1876',
    numeric: '388',
    totalDigits: 10,
  },
  {
    name: 'Japan',
    phoneCode: '+81',
    numeric: '392',
    totalDigits: 10,
  },
  {
    name: 'Jersey',
    phoneCode: '+44',
    numeric: '832',
    totalDigits: 10,
  },
  {
    name: 'Jordan',
    phoneCode: '+962',
    numeric: '400',
    totalDigits: 9,
  },
  {
    name: 'Kazakhstan',
    phoneCode: '+7',
    numeric: '398',
    totalDigits: 10,
  },
  {
    name: 'Kenya',
    phoneCode: '+254',
    numeric: '404',
    totalDigits: 9,
  },
  {
    name: 'Kiribati',
    phoneCode: '+686',
    numeric: '296',
    totalDigits: 5,
  },
  {
    name: 'Kuwait',
    phoneCode: '+965',
    numeric: '414',
    totalDigits: 8,
  },
  {
    name: 'Kyrgyzstan',
    phoneCode: '+996',
    numeric: '417',
    totalDigits: 9,
  },
  {
    name: 'Laos',
    phoneCode: '+856',
    numeric: '418',
    totalDigits: 9,
  },
  {
    name: 'Latvia',
    phoneCode: '+371',
    numeric: '428',
    totalDigits: 8,
  },
  {
    name: 'Lebanon',
    phoneCode: '+961',
    numeric: '422',
    totalDigits: 8,
  },
  {
    name: 'Lesotho',
    phoneCode: '+266',
    numeric: '426',
    totalDigits: 8,
  },
  {
    name: 'Liberia',
    phoneCode: '+231',
    numeric: '430',
    totalDigits: 8,
  },
  {
    name: 'Libya',
    phoneCode: '+218',
    numeric: '434',
    totalDigits: 9,
  },
  {
    name: 'Liechtenstein',
    phoneCode: '+423',
    numeric: '438',
    totalDigits: 7,
  },
  {
    name: 'Lithuania',
    phoneCode: '+370',
    numeric: '440',
    totalDigits: 8,
  },
  {
    name: 'Luxembourg',
    phoneCode: '+352',
    numeric: '442',
    totalDigits: 9,
  },
  {
    name: 'Macao',
    phoneCode: '+853',
    numeric: '446',
    totalDigits: 8,
  },
  {
    name: 'Madagascar',
    phoneCode: '+261',
    numeric: '450',
    totalDigits: 9,
  },
  {
    name: 'Malawi',
    phoneCode: '+265',
    numeric: '454',
    totalDigits: 9,
  },
  {
    name: 'Malaysia',
    phoneCode: '+60',
    numeric: '458',
    totalDigits: 9,
  },
  {
    name: 'Maldives',
    phoneCode: '+960',
    numeric: '462',
    totalDigits: 7,
  },
  {
    name: 'Mali',
    phoneCode: '+223',
    numeric: '466',
    totalDigits: 8,
  },
  {
    name: 'Malta',
    phoneCode: '+356',
    numeric: '470',
    totalDigits: 8,
  },
  {
    name: 'Marshall Islands',
    phoneCode: '+692',
    numeric: '584',
    totalDigits: 7,
  },
  {
    name: 'Martinique',
    phoneCode: '+596',
    numeric: '474',
    totalDigits: 9,
  },
  {
    name: 'Mauritania',
    phoneCode: '+222',
    numeric: '478',
    totalDigits: 8,
  },
  {
    name: 'Mauritius',
    phoneCode: '+230',
    numeric: '480',
    totalDigits: 7,
  },
  {
    name: 'Mayotte',
    phoneCode: '+262',
    numeric: '175',
    totalDigits: 9,
  },
  {
    name: 'Mexico',
    phoneCode: '+52',
    numeric: '484',
    totalDigits: 10,
  },
  {
    name: 'Micronesia',
    phoneCode: '+691',
    numeric: '583',
    totalDigits: 7,
  },
  {
    name: 'Moldova',
    phoneCode: '+373',
    numeric: '498',
    totalDigits: 8,
  },
  {
    name: 'Monaco',
    phoneCode: '+377',
    numeric: '492',
    totalDigits: 8,
  },
  {
    name: 'Mongolia',
    phoneCode: '+976',
    numeric: '496',
    totalDigits: 8,
  },
  {
    name: 'Montenegro',
    phoneCode: '+382',
    numeric: '499',
    totalDigits: 8,
  },
  {
    name: 'Montserrat',
    phoneCode: '+1664',
    numeric: '500',
    totalDigits: 10,
  },
  {
    name: 'Morocco',
    phoneCode: '+212',
    numeric: '504',
    totalDigits: 9,
  },
  {
    name: 'Mozambique',
    phoneCode: '+258',
    numeric: '508',
    totalDigits: 9,
  },
  {
    name: 'Myanmar',
    phoneCode: '+95',
    numeric: '104',
    totalDigits: 9,
  },
  {
    name: 'Namibia',
    phoneCode: '+264',
    numeric: '516',
    totalDigits: 9,
  },
  {
    name: 'Nauru',
    phoneCode: '+674',
    numeric: '520',
    totalDigits: 7,
  },
  {
    name: 'Nepal',
    phoneCode: '+977',
    numeric: '524',
    totalDigits: 10,
  },
  {
    name: 'Netherlands',
    phoneCode: '+31',
    numeric: '528',
    totalDigits: 9,
  },
  {
    name: 'New Caledonia',
    phoneCode: '+687',
    numeric: '540',
    totalDigits: 6,
  },
  {
    name: 'New Zealand',
    phoneCode: '+64',
    numeric: '554',
    totalDigits: 9,
  },
  {
    name: 'Nicaragua',
    phoneCode: '+505',
    numeric: '558',
    totalDigits: 8,
  },
  {
    name: 'Niger',
    phoneCode: '+227',
    numeric: '562',
    totalDigits: 8,
  },
  {
    name: 'Nigeria',
    phoneCode: '+234',
    numeric: '566',
    totalDigits: 10,
  },
  {
    name: 'Niue',
    phoneCode: '+683',
    numeric: '570',
    totalDigits: 4,
  },
  {
    name: 'Norfolk Island',
    phoneCode: '+672',
    numeric: '574',
    totalDigits: 5,
  },
  {
    name: 'North Korea',
    phoneCode: '+850',
    numeric: '408',
    totalDigits: 10,
  },
  {
    name: 'North Macedonia',
    phoneCode: '+389',
    numeric: '807',
    totalDigits: 8,
  },
  {
    name: 'Northern Mariana Islands',
    phoneCode: '+1670',
    numeric: '580',
    totalDigits: 10,
  },
  {
    name: 'Norway',
    phoneCode: '+47',
    numeric: '578',
    totalDigits: 8,
  },
  {
    name: 'Oman',
    phoneCode: '+968',
    numeric: '512',
    totalDigits: 8,
  },
  {
    name: 'Pakistan',
    phoneCode: '+92',
    numeric: '586',
    totalDigits: 10,
  },
  {
    name: 'Palau',
    phoneCode: '+680',
    numeric: '585',
    totalDigits: 7,
  },
  {
    name: 'Palestine',
    phoneCode: '+970',
    numeric: '275',
    totalDigits: 9,
  },
  {
    name: 'Panama',
    phoneCode: '+507',
    numeric: '591',
    totalDigits: 8,
  },
  {
    name: 'Papua New Guinea',
    phoneCode: '+675',
    numeric: '598',
    totalDigits: 8,
  },
  {
    name: 'Paraguay',
    phoneCode: '+595',
    numeric: '600',
    totalDigits: 9,
  },
  {
    name: 'Peru',
    phoneCode: '+51',
    numeric: '604',
    totalDigits: 9,
  },
  {
    name: 'Philippines',
    phoneCode: '+63',
    numeric: '608',
    totalDigits: 10,
  },
  {
    name: 'Pitcairn',
    phoneCode: '+64',
    numeric: '612',
    totalDigits: 9,
  },
  {
    name: 'Poland',
    phoneCode: '+48',
    numeric: '616',
    totalDigits: 9,
  },
  {
    name: 'Portugal',
    phoneCode: '+351',
    numeric: '620',
    totalDigits: 9,
  },
  {
    name: 'Puerto Rico',
    phoneCode: '+1787',
    numeric: '630',
    totalDigits: 10,
  },
  {
    name: 'Puerto Rico',
    phoneCode: '+1939',
    numeric: '630',
    totalDigits: 10,
  },
  {
    name: 'Qatar',
    phoneCode: '+974',
    numeric: '634',
    totalDigits: 8,
  },
  {
    name: 'Romania',
    phoneCode: '+40',
    numeric: '642',
    totalDigits: 9,
  },
  {
    name: 'Russia',
    phoneCode: '+7',
    numeric: '643',
    totalDigits: 10,
  },
  {
    name: 'Rwanda',
    phoneCode: '+250',
    numeric: '646',
    totalDigits: 9,
  },
  {
    name: 'Réunion',
    phoneCode: '+262',
    numeric: '638',
    totalDigits: 9,
  },
  {
    name: 'Saint Barthélemy',
    phoneCode: '+590',
    numeric: '652',
    totalDigits: 9,
  },
  {
    name: 'Saint Helena',
    phoneCode: '+290',
    numeric: '654',
    totalDigits: 5,
  },
  {
    name: 'Saint Kitts and Nevis',
    phoneCode: '+1869',
    numeric: '659',
    totalDigits: 10,
  },
  {
    name: 'Saint Lucia',
    phoneCode: '+1758',
    numeric: '662',
    totalDigits: 10,
  },
  {
    name: 'Saint Martin',
    phoneCode: '+590',
    numeric: '663',
    totalDigits: 9,
  },
  {
    name: 'Saint Pierre and Miquelon',
    phoneCode: '+508',
    numeric: '666',
    totalDigits: 6,
  },
  {
    name: 'Saint Vincent and the Grenadines',
    phoneCode: '+1784',
    numeric: '670',
    totalDigits: 10,
  },
  {
    name: 'Samoa',
    phoneCode: '+685',
    numeric: '882',
    totalDigits: 7,
  },
  {
    name: 'San Marino',
    phoneCode: '+378',
    numeric: '674',
    totalDigits: 10,
  },
  {
    name: 'Sao Tome and Principe',
    phoneCode: '+239',
    numeric: '678',
    totalDigits: 7,
  },
  {
    name: 'Saudi Arabia',
    phoneCode: '+966',
    numeric: '682',
    totalDigits: 9,
  },
  {
    name: 'Senegal',
    phoneCode: '+221',
    numeric: '686',
    totalDigits: 9,
  },
  {
    name: 'Serbia',
    phoneCode: '+381',
    numeric: '688',
    totalDigits: 9,
  },
  {
    name: 'Seychelles',
    phoneCode: '+248',
    numeric: '690',
    totalDigits: 8,
  },
  {
    name: 'Sierra Leone',
    phoneCode: '+232',
    numeric: '694',
    totalDigits: 8,
  },
  {
    name: 'Singapore',
    phoneCode: '+65',
    numeric: '702',
    totalDigits: 8,
  },
  {
    name: 'Sint Maarten',
    phoneCode: '+1721',
    numeric: '534',
    totalDigits: 10,
  },
  {
    name: 'Slovakia',
    phoneCode: '+421',
    numeric: '703',
    totalDigits: 9,
  },
  {
    name: 'Slovenia',
    phoneCode: '+386',
    numeric: '705',
    totalDigits: 8,
  },
  {
    name: 'Solomon Islands',
    phoneCode: '+677',
    numeric: '090',
    totalDigits: 7,
  },
  {
    name: 'Somalia',
    phoneCode: '+252',
    numeric: '706',
    totalDigits: 8,
  },
  {
    name: 'South Africa',
    phoneCode: '+27',
    numeric: '710',
    totalDigits: 9,
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    phoneCode: '+500',
    numeric: '239',
    totalDigits: 9,
  },
  {
    name: 'South Korea',
    phoneCode: '+82',
    numeric: '410',
    totalDigits: 9,
  },
  {
    name: 'South Sudan',
    phoneCode: '+211',
    numeric: '728',
    totalDigits: 9,
  },
  {
    name: 'Spain',
    phoneCode: '+34',
    numeric: '724',
    totalDigits: 9,
  },
  {
    name: 'Sri Lanka',
    phoneCode: '+94',
    numeric: '144',
    totalDigits: 9,
  },
  {
    name: 'Sudan',
    phoneCode: '+249',
    numeric: '736',
    totalDigits: 9,
  },
  {
    name: 'Suriname',
    phoneCode: '+597',
    numeric: '740',
    totalDigits: 7,
  },
  {
    name: 'Svalbard and Jan Mayen',
    phoneCode: '+47',
    numeric: '744',
    totalDigits: 8,
  },
  {
    name: 'Sweden',
    phoneCode: '+46',
    numeric: '752',
    totalDigits: 9,
  },
  {
    name: 'Switzerland',
    phoneCode: '+41',
    numeric: '756',
    totalDigits: 9,
  },
  {
    name: 'Syria',
    phoneCode: '+963',
    numeric: '760',
    totalDigits: 9,
  },
  {
    name: 'Taiwan',
    phoneCode: '+886',
    numeric: '158',
    totalDigits: 9,
  },
  {
    name: 'Tajikistan',
    phoneCode: '+992',
    numeric: '762',
    totalDigits: 9,
  },
  {
    name: 'Tanzania',
    phoneCode: '+255',
    numeric: '834',
    totalDigits: 9,
  },
  {
    name: 'Thailand',
    phoneCode: '+66',
    numeric: '764',
    totalDigits: 9,
  },
  {
    name: 'Togo',
    phoneCode: '+228',
    numeric: '768',
    totalDigits: 8,
  },
  {
    name: 'Tokelau',
    phoneCode: '+690',
    numeric: '772',
    totalDigits: 4,
  },
  {
    name: 'Tonga',
    phoneCode: '+676',
    numeric: '776',
    totalDigits: 5,
  },
  {
    name: 'Trinidad and Tobago',
    phoneCode: '+1868',
    numeric: '780',
    totalDigits: 10,
  },
  {
    name: 'Tunisia',
    phoneCode: '+216',
    numeric: '788',
    totalDigits: 8,
  },
  {
    name: 'Turkey',
    phoneCode: '+90',
    numeric: '792',
    totalDigits: 10,
  },
  {
    name: 'Turkmenistan',
    phoneCode: '+993',
    numeric: '795',
    totalDigits: 8,
  },
  {
    name: 'Turks and Caicos Islands',
    phoneCode: '+1649',
    numeric: '796',
    totalDigits: 10,
  },
  {
    name: 'Tuvalu',
    phoneCode: '+688',
    numeric: '798',
    totalDigits: 5,
  },
  {
    name: 'Uganda',
    phoneCode: '+256',
    numeric: '800',
    totalDigits: 9,
  },
  {
    name: 'Ukraine',
    phoneCode: '+380',
    numeric: '804',
    totalDigits: 9,
  },
  {
    name: 'United Arab Emirates',
    phoneCode: '+971',
    numeric: '784',
    totalDigits: 9,
  },
  {
    name: 'United Kingdom',
    phoneCode: '+44',
    numeric: '826',
    totalDigits: 10,
  },
  {
    name: 'United States',
    phoneCode: '+1',
    numeric: '840',
    totalDigits: 10,
  },
  {
    name: 'United States Minor Outlying Islands',
    phoneCode: '+1',
    numeric: '581',
    totalDigits: 10,
  },
  {
    name: 'Uruguay',
    phoneCode: '+598',
    numeric: '858',
    totalDigits: 8,
  },
  {
    name: 'Uzbekistan',
    phoneCode: '+998',
    numeric: '860',
    totalDigits: 9,
  },
  {
    name: 'Vanuatu',
    phoneCode: '+678',
    numeric: '548',
    totalDigits: 7,
  },
  {
    name: 'Vatican City',
    phoneCode: '+379',
    numeric: '336',
    totalDigits: 10,
  },
  {
    name: 'Venezuela',
    phoneCode: '+58',
    numeric: '862',
    totalDigits: 10,
  },
  {
    name: 'Vietnam',
    phoneCode: '+84',
    numeric: '704',
    totalDigits: 9,
  },
  {
    name: 'Virgin Islands (British)',
    phoneCode: '+1284',
    numeric: '092',
    totalDigits: 10,
  },
  {
    name: 'Virgin Islands (U.S.)',
    phoneCode: '+1340',
    numeric: '850',
    totalDigits: 10,
  },
  {
    name: 'Wallis and Futuna',
    phoneCode: '+681',
    numeric: '876',
    totalDigits: 5,
  },
  {
    name: 'Yemen',
    phoneCode: '+967',
    numeric: '887',
    totalDigits: 9,
  },
  {
    name: 'Zambia',
    phoneCode: '+260',
    numeric: '894',
    totalDigits: 9,
  },
  {
    name: 'Zimbabwe',
    phoneCode: '+263',
    numeric: '716',
    totalDigits: 9,
  },
];
